function out1 = uMaxSimulation
%uMaxSimulation
%    OUT1 = uMaxSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    29-Feb-2024 11:37:27

out1 = [8.4e+2;2.2e+2];
